print("To check the given first number is greater than the given second number or not")
value1 = float(input("First number:"))
value2 = float(input("Second number:"))
print(value1>=value2)
print("Sum of two Variables")
value1 = float(input("First number:"))
value2 = float(input("Second number:"))
print("Sum of the numbers=",value1+value2)
print("Area of a Square")
a = float(input("Side of the square in cm:"))
print("Area=",a*a,"cm^2")
print("Area of a Rectangle")
a = float(input("First side of the rectangle in cm:"))
b = float(input("Second side of the rectangle in cm:"))
print("Area=",a*b,"cm^2")
print("Average of two numbers")
value1 = float(input("First number:"))
value2 = float(input("Second number:"))
print("Average=",(value1+value2)/2)